import type { Metadata } from "next";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/common/app-sidebar";
import Header from "@/components/common/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-gray-200">
      <SidebarProvider>
        <AppSidebar />
        <main className="w-full flex flex-col min-h-screen">
          <Header />
          <div className="mx-1 my-4 xl:mx-8">{children}</div>
        </main>
      </SidebarProvider>
    </div>
  );
}
